services:
  # --- PostgreSQL Setup ---
  db-postgres:
    image: postgres:15-alpine
    container_name: ddd-crud-postgres
    environment:
      POSTGRES_DB: ddd_crud
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ddd-crud-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ddd_crud"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Go Application ---
  app:
    container_name: ddd-crud-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ":8080"
      LOGGER_LEVEL: "info"
      DATABASE_LOG_LEVEL: "info"
      DATABASE_DRIVER: "postgres"
      DATABASE_DSN: "host=db-postgres user=user password=password dbname=ddd_crud port=5432 sslmode=disable TimeZone=UTC"
    volumes:
      - .:/usr/src/app
    command: air -c /usr/src/app/.air.toml
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - ddd-crud-net

networks:
  ddd-crud-net:
    driver: bridge

volumes:
  postgres_data:
